// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package main

import (
	"github.com/gin-gonic/gin"
)

// Defines values for SetupPinRequestMode.
const (
	Input  SetupPinRequestMode = "input"
	Output SetupPinRequestMode = "output"
)

// AnalogWritePinRequest defines model for AnalogWritePinRequest.
type AnalogWritePinRequest struct {
	Pin   int `json:"pin"`
	Value int `json:"value"`
}

// AnalogWritePinResponse defines model for AnalogWritePinResponse.
type AnalogWritePinResponse struct {
	Pin   *int `json:"pin,omitempty"`
	Value *int `json:"value,omitempty"`
}

// ConnectRequest defines model for ConnectRequest.
type ConnectRequest struct {
	Port string `json:"port"`
}

// ConnectResponse defines model for ConnectResponse.
type ConnectResponse struct {
	Port      *string `json:"port,omitempty"`
	Timestamp *int    `json:"timestamp,omitempty"`
}

// DigitalWritePinRequest defines model for DigitalWritePinRequest.
type DigitalWritePinRequest struct {
	Pin   int `json:"pin"`
	Value int `json:"value"`
}

// DigitalWritePinResponse defines model for DigitalWritePinResponse.
type DigitalWritePinResponse struct {
	Pin   *int `json:"pin,omitempty"`
	Value *int `json:"value,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// Pong defines model for Pong.
type Pong struct {
	Ping string `json:"ping"`
}

// SetupPinRequest defines model for SetupPinRequest.
type SetupPinRequest struct {
	Mode SetupPinRequestMode `json:"mode"`
	Pin  int                 `json:"pin"`
}

// SetupPinRequestMode defines model for SetupPinRequest.Mode.
type SetupPinRequestMode string

// SetupPinResponse defines model for SetupPinResponse.
type SetupPinResponse struct {
	Mode *string `json:"mode,omitempty"`
	Pin  *int    `json:"pin,omitempty"`
}

// PostAnalogWritePinJSONRequestBody defines body for PostAnalogWritePin for application/json ContentType.
type PostAnalogWritePinJSONRequestBody = AnalogWritePinRequest

// PostConnectJSONRequestBody defines body for PostConnect for application/json ContentType.
type PostConnectJSONRequestBody = ConnectRequest

// PostDigitalWritePinJSONRequestBody defines body for PostDigitalWritePin for application/json ContentType.
type PostDigitalWritePinJSONRequestBody = DigitalWritePinRequest

// PostSetupPinJSONRequestBody defines body for PostSetupPin for application/json ContentType.
type PostSetupPinJSONRequestBody = SetupPinRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /analog_write_pin)
	PostAnalogWritePin(c *gin.Context)

	// (POST /connect)
	PostConnect(c *gin.Context)

	// (POST /digital_write_pin)
	PostDigitalWritePin(c *gin.Context)

	// (GET /ping)
	GetPing(c *gin.Context)

	// (POST /setup_pin)
	PostSetupPin(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAnalogWritePin operation middleware
func (siw *ServerInterfaceWrapper) PostAnalogWritePin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAnalogWritePin(c)
}

// PostConnect operation middleware
func (siw *ServerInterfaceWrapper) PostConnect(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostConnect(c)
}

// PostDigitalWritePin operation middleware
func (siw *ServerInterfaceWrapper) PostDigitalWritePin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostDigitalWritePin(c)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPing(c)
}

// PostSetupPin operation middleware
func (siw *ServerInterfaceWrapper) PostSetupPin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSetupPin(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/analog_write_pin", wrapper.PostAnalogWritePin)
	router.POST(options.BaseURL+"/connect", wrapper.PostConnect)
	router.POST(options.BaseURL+"/digital_write_pin", wrapper.PostDigitalWritePin)
	router.GET(options.BaseURL+"/ping", wrapper.GetPing)
	router.POST(options.BaseURL+"/setup_pin", wrapper.PostSetupPin)
}
