/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalogWritePinRequest
 */
export interface AnalogWritePinRequest {
    /**
     * 
     * @type {number}
     * @memberof AnalogWritePinRequest
     */
    pin: number;
    /**
     * 
     * @type {number}
     * @memberof AnalogWritePinRequest
     */
    value: number;
}

/**
 * Check if a given object implements the AnalogWritePinRequest interface.
 */
export function instanceOfAnalogWritePinRequest(value: object): value is AnalogWritePinRequest {
    if (!('pin' in value) || value['pin'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AnalogWritePinRequestFromJSON(json: any): AnalogWritePinRequest {
    return AnalogWritePinRequestFromJSONTyped(json, false);
}

export function AnalogWritePinRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalogWritePinRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pin': json['pin'],
        'value': json['value'],
    };
}

export function AnalogWritePinRequestToJSON(value?: AnalogWritePinRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pin': value['pin'],
        'value': value['value'],
    };
}

