/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalogWritePinResponse
 */
export interface AnalogWritePinResponse {
    /**
     * 
     * @type {number}
     * @memberof AnalogWritePinResponse
     */
    pin?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalogWritePinResponse
     */
    value?: number;
}

/**
 * Check if a given object implements the AnalogWritePinResponse interface.
 */
export function instanceOfAnalogWritePinResponse(value: object): value is AnalogWritePinResponse {
    return true;
}

export function AnalogWritePinResponseFromJSON(json: any): AnalogWritePinResponse {
    return AnalogWritePinResponseFromJSONTyped(json, false);
}

export function AnalogWritePinResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalogWritePinResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pin': json['pin'] == null ? undefined : json['pin'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function AnalogWritePinResponseToJSON(value?: AnalogWritePinResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pin': value['pin'],
        'value': value['value'],
    };
}

