/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PinResponse } from './PinResponse';
import {
    PinResponseFromJSON,
    PinResponseFromJSONTyped,
    PinResponseToJSON,
} from './PinResponse';

/**
 * 
 * @export
 * @interface BoardResponse
 */
export interface BoardResponse {
    /**
     * 
     * @type {Array<PinResponse>}
     * @memberof BoardResponse
     */
    pins?: Array<PinResponse>;
}

/**
 * Check if a given object implements the BoardResponse interface.
 */
export function instanceOfBoardResponse(value: object): value is BoardResponse {
    return true;
}

export function BoardResponseFromJSON(json: any): BoardResponse {
    return BoardResponseFromJSONTyped(json, false);
}

export function BoardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pins': json['pins'] == null ? undefined : ((json['pins'] as Array<any>).map(PinResponseFromJSON)),
    };
}

export function BoardResponseToJSON(value?: BoardResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pins': value['pins'] == null ? undefined : ((value['pins'] as Array<any>).map(PinResponseToJSON)),
    };
}

