/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoardsResponse
 */
export interface BoardsResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof BoardsResponse
     */
    boards: Array<string>;
}

/**
 * Check if a given object implements the BoardsResponse interface.
 */
export function instanceOfBoardsResponse(value: object): value is BoardsResponse {
    if (!('boards' in value) || value['boards'] === undefined) return false;
    return true;
}

export function BoardsResponseFromJSON(json: any): BoardsResponse {
    return BoardsResponseFromJSONTyped(json, false);
}

export function BoardsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'boards': json['boards'],
    };
}

export function BoardsResponseToJSON(value?: BoardsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'boards': value['boards'],
    };
}

