/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PinResponse } from './PinResponse';
import {
    PinResponseFromJSON,
    PinResponseFromJSONTyped,
    PinResponseToJSON,
} from './PinResponse';

/**
 * 
 * @export
 * @interface CircuitResponse
 */
export interface CircuitResponse {
    /**
     * 
     * @type {Array<PinResponse>}
     * @memberof CircuitResponse
     */
    pins: Array<PinResponse>;
}

/**
 * Check if a given object implements the CircuitResponse interface.
 */
export function instanceOfCircuitResponse(value: object): value is CircuitResponse {
    if (!('pins' in value) || value['pins'] === undefined) return false;
    return true;
}

export function CircuitResponseFromJSON(json: any): CircuitResponse {
    return CircuitResponseFromJSONTyped(json, false);
}

export function CircuitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CircuitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pins': ((json['pins'] as Array<any>).map(PinResponseFromJSON)),
    };
}

export function CircuitResponseToJSON(value?: CircuitResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pins': ((value['pins'] as Array<any>).map(PinResponseToJSON)),
    };
}

