/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectResponse
 */
export interface ConnectResponse {
    /**
     * 
     * @type {string}
     * @memberof ConnectResponse
     */
    port?: string;
    /**
     * 
     * @type {number}
     * @memberof ConnectResponse
     */
    timestamp?: number;
}

/**
 * Check if a given object implements the ConnectResponse interface.
 */
export function instanceOfConnectResponse(value: object): value is ConnectResponse {
    return true;
}

export function ConnectResponseFromJSON(json: any): ConnectResponse {
    return ConnectResponseFromJSONTyped(json, false);
}

export function ConnectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'port': json['port'] == null ? undefined : json['port'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function ConnectResponseToJSON(value?: ConnectResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'port': value['port'],
        'timestamp': value['timestamp'],
    };
}

