/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectRequest
 */
export interface ConnectRequest {
    /**
     * 
     * @type {string}
     * @memberof ConnectRequest
     */
    port: string;
}

/**
 * Check if a given object implements the ConnectRequest interface.
 */
export function instanceOfConnectRequest(value: object): value is ConnectRequest {
    if (!('port' in value) || value['port'] === undefined) return false;
    return true;
}

export function ConnectRequestFromJSON(json: any): ConnectRequest {
    return ConnectRequestFromJSONTyped(json, false);
}

export function ConnectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'port': json['port'],
    };
}

export function ConnectRequestToJSON(value?: ConnectRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'port': value['port'],
    };
}

