/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCircuitResponse
 */
export interface CreateCircuitResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCircuitResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCircuitResponse
     */
    board: CreateCircuitResponseBoardEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateCircuitResponse
     */
    timestamp: number;
}


/**
 * @export
 */
export const CreateCircuitResponseBoardEnum = {
    ArduinoNano: 'arduino_nano'
} as const;
export type CreateCircuitResponseBoardEnum = typeof CreateCircuitResponseBoardEnum[keyof typeof CreateCircuitResponseBoardEnum];


/**
 * Check if a given object implements the CreateCircuitResponse interface.
 */
export function instanceOfCreateCircuitResponse(value: object): value is CreateCircuitResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('board' in value) || value['board'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function CreateCircuitResponseFromJSON(json: any): CreateCircuitResponse {
    return CreateCircuitResponseFromJSONTyped(json, false);
}

export function CreateCircuitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCircuitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'board': json['board'],
        'timestamp': json['timestamp'],
    };
}

export function CreateCircuitResponseToJSON(value?: CreateCircuitResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'board': value['board'],
        'timestamp': value['timestamp'],
    };
}

