/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCircuitRequest
 */
export interface CreateCircuitRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCircuitRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCircuitRequest
     */
    board: CreateCircuitRequestBoardEnum;
}


/**
 * @export
 */
export const CreateCircuitRequestBoardEnum = {
    ArduinoNano: 'arduino_nano'
} as const;
export type CreateCircuitRequestBoardEnum = typeof CreateCircuitRequestBoardEnum[keyof typeof CreateCircuitRequestBoardEnum];


/**
 * Check if a given object implements the CreateCircuitRequest interface.
 */
export function instanceOfCreateCircuitRequest(value: object): value is CreateCircuitRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('board' in value) || value['board'] === undefined) return false;
    return true;
}

export function CreateCircuitRequestFromJSON(json: any): CreateCircuitRequest {
    return CreateCircuitRequestFromJSONTyped(json, false);
}

export function CreateCircuitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCircuitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'board': json['board'],
    };
}

export function CreateCircuitRequestToJSON(value?: CreateCircuitRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'board': value['board'],
    };
}

