/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DelayPostRequest
 */
export interface DelayPostRequest {
    /**
     * 
     * @type {number}
     * @memberof DelayPostRequest
     */
    delay: number;
}

/**
 * Check if a given object implements the DelayPostRequest interface.
 */
export function instanceOfDelayPostRequest(value: object): value is DelayPostRequest {
    if (!('delay' in value) || value['delay'] === undefined) return false;
    return true;
}

export function DelayPostRequestFromJSON(json: any): DelayPostRequest {
    return DelayPostRequestFromJSONTyped(json, false);
}

export function DelayPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DelayPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'delay': json['delay'],
    };
}

export function DelayPostRequestToJSON(value?: DelayPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'delay': value['delay'],
    };
}

