/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigitalWritePinRequest
 */
export interface DigitalWritePinRequest {
    /**
     * 
     * @type {number}
     * @memberof DigitalWritePinRequest
     */
    pin: number;
    /**
     * 
     * @type {number}
     * @memberof DigitalWritePinRequest
     */
    value: number;
}

/**
 * Check if a given object implements the DigitalWritePinRequest interface.
 */
export function instanceOfDigitalWritePinRequest(value: object): value is DigitalWritePinRequest {
    if (!('pin' in value) || value['pin'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function DigitalWritePinRequestFromJSON(json: any): DigitalWritePinRequest {
    return DigitalWritePinRequestFromJSONTyped(json, false);
}

export function DigitalWritePinRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigitalWritePinRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pin': json['pin'],
        'value': json['value'],
    };
}

export function DigitalWritePinRequestToJSON(value?: DigitalWritePinRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pin': value['pin'],
        'value': value['value'],
    };
}

