/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PinResponse
 */
export interface PinResponse {
    /**
     * 
     * @type {number}
     * @memberof PinResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PinResponse
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof PinResponse
     */
    mode: number;
    /**
     * 
     * @type {number}
     * @memberof PinResponse
     */
    min: number;
    /**
     * 
     * @type {number}
     * @memberof PinResponse
     */
    max: number;
    /**
     * 
     * @type {boolean}
     * @memberof PinResponse
     */
    digitalRead: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PinResponse
     */
    digitalWrite: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PinResponse
     */
    analogRead: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PinResponse
     */
    analogWrite: boolean;
}

/**
 * Check if a given object implements the PinResponse interface.
 */
export function instanceOfPinResponse(value: object): value is PinResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('min' in value) || value['min'] === undefined) return false;
    if (!('max' in value) || value['max'] === undefined) return false;
    if (!('digitalRead' in value) || value['digitalRead'] === undefined) return false;
    if (!('digitalWrite' in value) || value['digitalWrite'] === undefined) return false;
    if (!('analogRead' in value) || value['analogRead'] === undefined) return false;
    if (!('analogWrite' in value) || value['analogWrite'] === undefined) return false;
    return true;
}

export function PinResponseFromJSON(json: any): PinResponse {
    return PinResponseFromJSONTyped(json, false);
}

export function PinResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PinResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'mode': json['mode'],
        'min': json['min'],
        'max': json['max'],
        'digitalRead': json['digitalRead'],
        'digitalWrite': json['digitalWrite'],
        'analogRead': json['analogRead'],
        'analogWrite': json['analogWrite'],
    };
}

export function PinResponseToJSON(value?: PinResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': value['type'],
        'mode': value['mode'],
        'min': value['min'],
        'max': value['max'],
        'digitalRead': value['digitalRead'],
        'digitalWrite': value['digitalWrite'],
        'analogRead': value['analogRead'],
        'analogWrite': value['analogWrite'],
    };
}

