/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PWMRequest
 */
export interface PWMRequest {
    /**
     * 
     * @type {number}
     * @memberof PWMRequest
     */
    pin: number;
    /**
     * 
     * @type {number}
     * @memberof PWMRequest
     */
    dutyCycle: number;
    /**
     * 
     * @type {number}
     * @memberof PWMRequest
     */
    period: number;
}

/**
 * Check if a given object implements the PWMRequest interface.
 */
export function instanceOfPWMRequest(value: object): value is PWMRequest {
    if (!('pin' in value) || value['pin'] === undefined) return false;
    if (!('dutyCycle' in value) || value['dutyCycle'] === undefined) return false;
    if (!('period' in value) || value['period'] === undefined) return false;
    return true;
}

export function PWMRequestFromJSON(json: any): PWMRequest {
    return PWMRequestFromJSONTyped(json, false);
}

export function PWMRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PWMRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pin': json['pin'],
        'dutyCycle': json['duty_cycle'],
        'period': json['period'],
    };
}

export function PWMRequestToJSON(value?: PWMRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pin': value['pin'],
        'duty_cycle': value['dutyCycle'],
        'period': value['period'],
    };
}

