/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveCircuitRequest
 */
export interface SaveCircuitRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveCircuitRequest
     */
    id: number;
}

/**
 * Check if a given object implements the SaveCircuitRequest interface.
 */
export function instanceOfSaveCircuitRequest(value: object): value is SaveCircuitRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SaveCircuitRequestFromJSON(json: any): SaveCircuitRequest {
    return SaveCircuitRequestFromJSONTyped(json, false);
}

export function SaveCircuitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveCircuitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function SaveCircuitRequestToJSON(value?: SaveCircuitRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

