/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetupPinRequest
 */
export interface SetupPinRequest {
    /**
     * 
     * @type {number}
     * @memberof SetupPinRequest
     */
    pin: number;
    /**
     * 
     * @type {string}
     * @memberof SetupPinRequest
     */
    mode: string;
}

/**
 * Check if a given object implements the SetupPinRequest interface.
 */
export function instanceOfSetupPinRequest(value: object): value is SetupPinRequest {
    if (!('pin' in value) || value['pin'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function SetupPinRequestFromJSON(json: any): SetupPinRequest {
    return SetupPinRequestFromJSONTyped(json, false);
}

export function SetupPinRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupPinRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pin': json['pin'],
        'mode': json['mode'],
    };
}

export function SetupPinRequestToJSON(value?: SetupPinRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pin': value['pin'],
        'mode': value['mode'],
    };
}

