/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetupPinResponse
 */
export interface SetupPinResponse {
    /**
     * 
     * @type {number}
     * @memberof SetupPinResponse
     */
    pin?: number;
    /**
     * 
     * @type {string}
     * @memberof SetupPinResponse
     */
    mode?: string;
}

/**
 * Check if a given object implements the SetupPinResponse interface.
 */
export function instanceOfSetupPinResponse(value: object): value is SetupPinResponse {
    return true;
}

export function SetupPinResponseFromJSON(json: any): SetupPinResponse {
    return SetupPinResponseFromJSONTyped(json, false);
}

export function SetupPinResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupPinResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pin': json['pin'] == null ? undefined : json['pin'],
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function SetupPinResponseToJSON(value?: SetupPinResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pin': value['pin'],
        'mode': value['mode'],
    };
}

