/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WritePinResponse
 */
export interface WritePinResponse {
    /**
     * 
     * @type {number}
     * @memberof WritePinResponse
     */
    pin?: number;
    /**
     * 
     * @type {number}
     * @memberof WritePinResponse
     */
    value?: number;
}

/**
 * Check if a given object implements the WritePinResponse interface.
 */
export function instanceOfWritePinResponse(value: object): value is WritePinResponse {
    return true;
}

export function WritePinResponseFromJSON(json: any): WritePinResponse {
    return WritePinResponseFromJSONTyped(json, false);
}

export function WritePinResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WritePinResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pin': json['pin'] == null ? undefined : json['pin'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function WritePinResponseToJSON(value?: WritePinResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pin': value['pin'],
        'value': value['value'],
    };
}

