-- CreateTable
CREATE TABLE "CircuitDB" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "board" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "SketchDB" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "PinDB" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "pinNumber" INTEGER NOT NULL,
    "mode" INTEGER NOT NULL DEFAULT 0,
    "circuitId" INTEGER NOT NULL,
    CONSTRAINT "PinDB_circuitId_fkey" FOREIGN KEY ("circuitId") REFERENCES "CircuitDB" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
