/* tslint:disable */
/* eslint-disable */
/**
 * tobro_http_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConnectRequest,
  ConnectResponse,
  DelayPostRequest,
  ErrorResponse,
  Pong,
  SetupPinRequest,
  SetupPinResponse,
  WritePinRequest,
  WritePinResponse,
} from '../models/index';
import {
    ConnectRequestFromJSON,
    ConnectRequestToJSON,
    ConnectResponseFromJSON,
    ConnectResponseToJSON,
    DelayPostRequestFromJSON,
    DelayPostRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PongFromJSON,
    PongToJSON,
    SetupPinRequestFromJSON,
    SetupPinRequestToJSON,
    SetupPinResponseFromJSON,
    SetupPinResponseToJSON,
    WritePinRequestFromJSON,
    WritePinRequestToJSON,
    WritePinResponseFromJSON,
    WritePinResponseToJSON,
} from '../models/index';

export interface ConnectPostRequest {
    connectRequest?: ConnectRequest;
}

export interface DelayPostOperationRequest {
    delayPostRequest?: DelayPostRequest;
}

export interface SetupPinPostRequest {
    setupPinRequest?: SetupPinRequest;
}

export interface WritePinPostRequest {
    writePinRequest?: WritePinRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async connectPostRaw(requestParameters: ConnectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/connect`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConnectRequestToJSON(requestParameters['connectRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectResponseFromJSON(jsonValue));
    }

    /**
     */
    async connectPost(requestParameters: ConnectPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectResponse> {
        const response = await this.connectPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async delayPostRaw(requestParameters: DelayPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Pong>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/delay`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DelayPostRequestToJSON(requestParameters['delayPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PongFromJSON(jsonValue));
    }

    /**
     */
    async delayPost(requestParameters: DelayPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Pong> {
        const response = await this.delayPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async pingGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Pong>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ping`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PongFromJSON(jsonValue));
    }

    /**
     */
    async pingGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Pong> {
        const response = await this.pingGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async setupPinPostRaw(requestParameters: SetupPinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SetupPinResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/setup_pin`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetupPinRequestToJSON(requestParameters['setupPinRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetupPinResponseFromJSON(jsonValue));
    }

    /**
     */
    async setupPinPost(requestParameters: SetupPinPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SetupPinResponse> {
        const response = await this.setupPinPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async writePinPostRaw(requestParameters: WritePinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WritePinResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/write_pin`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WritePinRequestToJSON(requestParameters['writePinRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WritePinResponseFromJSON(jsonValue));
    }

    /**
     */
    async writePinPost(requestParameters: WritePinPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WritePinResponse> {
        const response = await this.writePinPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
