openapi: "3.0.0"
info:
  version: 1.0.0
  title: tobro_http_server
paths:
  /ping:
    get:
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
  /connect:
    post:
      requestBody:
        description: Connect to a serial port
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectRequest'
      responses:
        '200':
          description: Connect post response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectResponse'
        '400':
          description: Connect post error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /create_circuit:
    post:
      requestBody:
        description: Create a circuit
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCircuitRequest'
      responses:
        '200':
          description: Create circuit post response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCircuitResponse'
        '400':
          description: Create circuit post error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /setup_pin:
    post:
      requestBody:
        description: Setup a pin
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetupPinRequest'
      responses:
        '200':
          description: Setup pin post response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetupPinResponse'
        '400':
          description: Setup pin post error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /digital_write_pin:
    post:
      requestBody:
        description: Write to a pin
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DigitalWritePinRequest'
      responses:
        '200':
          description: Write pin post response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitalWritePinResponse'
        '400':
          description: Write pin post error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /analog_write_pin:
    post:
      requestBody:
        description: Write to a pin
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalogWritePinRequest'
      responses:
        '200':
          description: Write pin post response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalogWritePinResponse'
        '400':
          description: Write pin post error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    # base types
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
    ErrorResponse:
      type: object
      required:
        - success
      properties:
        message:
          type: string
    ConnectRequest:
      type: object
      required:
        - port
      properties:
        port:
          type: string
          example: "/dev/ttyUSB0"
    ConnectResponse:
      type: object
      properties:
        port:
          type: string
          example: "/dev/ttyUSB0"
        timestamp:
          type: integer
          example: 1612345678
    CreateCircuitRequest:
      type: object
      required:
        - name
        - board
      properties:
        name:
          type: string
          example: "my_circuit"
        board:
          enum:
            - "arduino_nano"
          example: "arduino_nano"
    CreateCircuitResponse:
      type: object
      properties:
        name:
          type: string
          example: "my_circuit"
        board:
          type: string
          example: "arduino_nano"
        timestamp:
          type: integer
          example: 1612345678
    SetupPinRequest:
      type: object
      required:
        - pin
        - mode
      properties:
        pin:
          type: integer
          example: 1
        mode:
          type: string
          enum:
            - "input"
            - "output"
    SetupPinResponse:
      type: object
      properties:
        pin:
          type: integer
          example: 1
        mode:
          type: string
    DigitalWritePinRequest:
      type: object
      required:
        - pin
        - value
      properties:
        pin:
          type: integer
          example: 1
        value:
          type: integer
          minimum: 0
          maximum: 1
    DigitalWritePinResponse:
      type: object
      properties:
        pin:
          type: integer
          example: 1
        value:
          type: integer
          minimum: 0
          maximum: 1
    AnalogWritePinRequest:
      type: object
      required:
        - pin
        - value
      properties:
        pin:
          type: integer
          example: 1
        value:
          type: integer
          minimum: 0
          maximum: 255
    AnalogWritePinResponse:
      type: object
      properties:
        pin:
          type: integer
          example: 1
        value:
          type: integer
          minimum: 0
          maximum: 255